apiVersion: v1
kind: Service
metadata:
  name: greenhouse-soil-temperature
spec:
  type: NodePort
  ports:
    - port: 5300
      protocol: TCP
      targetPort: 5300
  selector:
    app: greenhouse-soil-temperature
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: greenhouse-soil-temperature
  name: greenhouse-soil-temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse-soil-temperature
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greenhouse-soil-temperature
    spec:
      containers:
        - env:
            - name: PORT
              value: "5300"
          image: mcpomm/greenhouse-soil-temperature:0.0.2
          name: greenhouse-soil-temperature
          ports:
            - containerPort: 5300
          securityContext:
            privileged: true
status: {}
