apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: greenhouse-manager
  name: greenhouse-manager
spec:
  containers:
    - env:
        - name: CONFIG
          value: production
      image: mcpomm/greenhouse-manager:0.0.9
      name: greenhouse-manager
      envFrom:
        - secretRef:
            name: thing-speak-secret
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
