apiVersion: v1
kind: Service
metadata:
  name: greenhouse-temperature
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: greenhouse-temperature
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: greenhouse-temperature
  name: greenhouse-temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse-temperature
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greenhouse-temperature
    spec:
      containers:
        - env:
            - name: PORT
              value: "5000"
          image: mcpomm/greenhouse-temperature:0.0.3
          name: greenhouse-temperature
          ports:
            - containerPort: 5000
          securityContext:
            privileged: true
status: {}
