apiVersion: v1
kind: Service
metadata:
  name: greenhouse-temperature
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    run: greenhouse-temperature
---

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: greenhouse-temperature
  name: greenhouse-temperature
spec:
  containers:
    - env:
        - name: PORT
          value: "5000"
      image: mcpomm/greenhouse-temperature:0.0.3
      name: greenhouse-temperature
      ports:
        - containerPort: 5000
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
