apiVersion: v1
kind: Service
metadata:
  name: greenhouse-soil-temperature
spec:
  type: NodePort
  ports:
    - port: 5300
      protocol: TCP
      targetPort: 5300
  selector:
    run: greenhouse-soil-temperature
---

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: greenhouse-soil-temperature
  name: greenhouse-soil-temperature
spec:
  containers:
    - env:
        - name: PORT
          value: "5300"
      image: mcpomm/greenhouse-soil-temperature:0.0.2
      name: greenhouse-soil-temperature
      ports:
        - containerPort: 5300
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
