apiVersion: v1
kind: Service
metadata:
  name: greenhouse-humidity
spec:
  type: NodePort
  ports:
    - port: 5100
      protocol: TCP
      targetPort: 5100
  selector:
    run: greenhouse-humidity
---

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: greenhouse-humidity
  name: greenhouse-humidity
spec:
  containers:
    - env:
        - name: PORT
          value: "5100"
      image: mcpomm/greenhouse-humidity:latest
      name: greenhouse-humidity
      ports:
        - containerPort: 5100
      resources: {}
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
