apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: humidity
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    run: humidity
status:
  loadBalancer: {}
---

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: humidity
  name: humidity
spec:
  containers:
    - env:
        - name: PORT
          value: "5001"
      image: mcpomm/greenhouse-humidity:latest
      name: humidity
      ports:
        - containerPort: 5001
      resources: {}
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
